# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ec841a5c814becde1cd24734d3581ebc30b18b8500487afd0efc454fcf51916a949a485d639f0c15ae777b26029a81c52f2eabacd47309c820a6fa1dc566015

test:
  secret_key_base: d166ed24f4748376821966daf41aa5296ccef66b3b5b2220c4bd7a40d67f3248d18882f34223bf85e5f8689921e71ddbc3c98d99d358971ff70f2cbcfe91c4a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
